// Minifigures
export const GET_MINIFIGURES = 'GET_MINIFIGURES';
export const GET_MINIFIGURES_SUCCESS = `${GET_MINIFIGURES}/SUCCESS`;
export const GET_MINIFIGURES_ERROR = `${GET_MINIFIGURES}/ERROR`;

export const ADD_MINIFIGURE = 'ADD_MINIFIGURE';
export const ADD_MINIFIGURE_SUCCESS = `${ADD_MINIFIGURE}/SUCCESS`;
export const ADD_MINIFIGURE_ERROR = `${ADD_MINIFIGURE}/ERROR`;

export const UPDATE_MINIFIGURE = 'UPDATE_MINIFIGURE';
export const UPDATE_MINIFIGURE_SUCCESS = `${UPDATE_MINIFIGURE}/SUCCESS`;
export const UPDATE_MINIFIGURE_ERROR = `${UPDATE_MINIFIGURE}/ERROR`;

export const DELETE_MINIFIGURE = 'DELETE_MINIFIGURE';
export const DELETE_MINIFIGURE_SUCCESS = `${DELETE_MINIFIGURE}/SUCCESS`;
export const DELETE_MINIFIGURE_ERROR = `${DELETE_MINIFIGURE}/ERROR`;

// Sets
export const GET_SETS = 'GET_SETS';
export const GET_SETS_SUCCESS = `${GET_SETS}/SUCCESS`;
export const GET_SETS_ERROR = `${GET_SETS}/ERROR`;

export const ADD_SET = 'ADD_SET';
export const ADD_SET_SUCCESS = `${ADD_SET}/SUCCESS`;
export const ADD_SET_ERROR = `${ADD_SET}/ERROR`;

export const UPDATE_SET = 'UPDATE_SET';
export const UPDATE_SET_SUCCESS = `${UPDATE_SET}/SUCCESS`;
export const UPDATE_SET_ERROR = `${UPDATE_SET}/ERROR`;

export const DELETE_SET = 'DELETE_SET';
export const DELETE_SET_SUCCESS = `${DELETE_SET}/SUCCESS`;
export const DELETE_SET_ERROR = `${DELETE_SET}/ERROR`;

// Tools
export const GET_DOLLAR_RATE = 'GET_DOLLAR_RATE';
export const GET_THEMES = 'GET_THEMES';
export const SET_DARK_MODE = 'SET_DARK_MODE';
export const GET_IS_MOBILE = 'GET_IS_MOBILE';
export const SET_LAYOUT = 'SET_LAYOUT';
