export const GET_MINIFIGURES = 'GET_MINIFIGURES';
export const GET_MINIFIGURES_SUCCESS = `${GET_MINIFIGURES}/SUCCESS`;
export const GET_MINIFIGURES_ERROR = `${GET_MINIFIGURES}/ERROR`;

export const SET_MINIFIGURES = 'ADD_MINIFIGURE';
export const SET_MINIFIGURES_SUCCESS = `${SET_MINIFIGURES}/SUCCESS`;
export const SET_MINIFIGURES_ERROR = `${SET_MINIFIGURES}/ERROR`;

export const DELETE_MINIFIGURES = 'DELETE_MINIFIGURE';
export const DELETE_MINIFIGURES_SUCCESS = `${DELETE_MINIFIGURES}/SUCCESS`;
export const DELETE_MINIFIGURES_ERROR = `${DELETE_MINIFIGURES}/ERROR`;

export const GET_SETS = 'GET_SETS';
export const SET_SETS = 'ADD_SET';

export const GET_DOLLAR_RATE = 'GET_DOLLAR_RATE';
export const GET_THEMES = 'GET_THEMES';
